language: node_js

branches:
  only:
    - master

env:
  NO_REPLICA_SETS=true

node_js:
  - "0.12"
  - "0.11"

services:
  - mongodb

before_script:
  - "npm install -g gulp"
  - "npm install"

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com