language: node_js

branches:
  only:
    - master

env:
  NO_REPLICA_SETS=true

node_js:
  - "4"
  - "6"

services:
  - mongodb

before_script:
  - "npm install -g gulp"
  - "sleep 5"

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com